spring:
    #热部署配置
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    #数据库连接池配置
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.96.66.66:3306/tlong?useUnicode=true&characterEncoding=utf8
        username: root
        password: mypassword

server:
  port: 8085